# Generated by Django 6.1 on 2026-08-24 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_remove_review_comments_re_approve_83c5c7_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('text', models.TextField(max_length=2000)),
                ('rating', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='comments_co_status_2720ea_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='comments_co_status_08b9ef_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='comments_co_user_id_063857_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='comments_co_rating_ef6500_idx',
        ),
        migrations.AddField(
            model_name='review',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['status'], name='comments_re_status_c85be4_idx'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
