import uuid

from django.conf import settings
from django.db import models
from django.utils import timezone

from . import constants as c

TRIAGE_LEVEL_CHOICES = [
    (c.UNKNOWN, "Unknown"),
    (c.OUT_OF_SCOPE, "Out of scope"),
    (c.LOW_PRIORITY, "Low priority"),
    (c.HIGH_PRIORITY, "High priority"),
    (c.URGENT, "Urgent"),
]


class ChatSession(models.Model):
    """
    One row per chat widget session. The backend is the single source of truth
    for a session (API.md §1): the AI Service stores nothing.
    """

    # Key sent by the chat widget. It is only used for lookups on our side.
    session_id = models.CharField(max_length=100, unique=True)

    # The ID we send to the AI Service as `session_id`. Generated by the backend,
    # so it can never contain personal data (§10).
    ai_session_id = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="chat_sessions",
    )

    # The `triage` object from the most recent successful AI Service response,
    # stored so it can be sent back unchanged (§4.1). NULL level = no successful
    # response yet, which is sent as `triage: null`.
    triage_level = models.CharField(
        max_length=20, choices=TRIAGE_LEVEL_CHOICES, null=True, blank=True
    )
    # For clinic staff only. Never shown to the patient (§4.6).
    triage_summary = models.TextField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-updated_at"]

    def __str__(self):
        return self.session_id


class ChatMessage(models.Model):
    USER = "user"
    ASSISTANT = "assistant"
    BACKEND = "backend"
    ROLE_CHOICES = [
        (USER, "Patient"),
        (ASSISTANT, "AI Service reply"),
        (BACKEND, "Backend generated"),
    ]

    # Kinds of backend-generated messages.
    FALLBACK = "fallback"
    KIND_CHOICES = [
        (FALLBACK, "Fallback message"),
    ]

    session = models.ForeignKey(ChatSession, on_delete=models.CASCADE, related_name="messages")

    # `user` and `assistant` are the only roles that may be sent as `history` (§4.3).
    # `backend` messages (fallbacks, and later visit codes / confirmations) are kept for the
    # conversation record but MUST NOT be sent to the AI Service.
    role = models.CharField(max_length=10, choices=ROLE_CHOICES)
    kind = models.CharField(max_length=30, choices=KIND_CHOICES, blank=True, default="")
    content = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ["created_at", "id"]
        indexes = [models.Index(fields=["session", "id"])]

    def __str__(self):
        return f"[{self.role}] {self.content[:40]}"
