# Generated by Django 6.0.5 on 2026-10-05 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات کوتاه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی مقاله',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای مقالات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(allow_unicode=True, max_length=280, unique=True)),
                ('excerpt', models.TextField(blank=True, default='', max_length=600)),
                ('content', models.TextField(verbose_name='متن کامل (HTML ضدعفونی\u200cشده)')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='articles/covers/%Y/%m/')),
                ('video_embed_url', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشرشده')], default='draft', max_length=20)),
                ('reading_time_minutes', models.PositiveSmallIntegerField(default=1)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.category')),
            ],
            options={
                'verbose_name': 'مقاله پزشکی',
                'verbose_name_plural': 'مقالات پزشکی',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='articles_ar_status_de59cf_idx')],
            },
        ),
    ]
