# Generated by Django 6.0.3 on 2026-03-15 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], help_text='The day of the week this rule applies to.', max_length=3, unique=True)),
                ('start_time', models.TimeField(help_text="The start time of the doctor's availability on this day.")),
                ('end_time', models.TimeField(help_text="The end time of the doctor's availability on this day.")),
                ('visit_duration', models.PositiveIntegerField(help_text='Duration of each visit in minutes (e.g., 15). Must be a positive value.')),
                ('time_gap', models.PositiveIntegerField(default=0, help_text='Gap between consecutive visits in minutes (e.g., 5). Must be a positive value or zero.')),
                ('is_active', models.BooleanField(default=True, help_text='Is this availability rule currently active and in effect?')),
            ],
            options={
                'verbose_name_plural': 'Doctor Availabilities',
                'ordering': ['day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='The start date of the closure period.')),
                ('end_date', models.DateField(help_text="The end date of the closure period. If it's a single day, start_date and end_date should be the same.")),
                ('reason', models.CharField(blank=True, help_text="Reason for the exception (e.g., Holiday, Doctor's leave, Clinic maintenance).", max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Availability Exceptions',
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='end_date_after_start_date')],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(help_text='The date of the appointment.')),
                ('appointment_time', models.TimeField(help_text='The time of the appointment.')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled_user', 'Cancelled by User'), ('cancelled_admin', 'Cancelled by Admin'), ('visited', 'Visited')], default='scheduled', help_text='The current status of the appointment.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the appointment was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the appointment was last updated.')),
                ('user', models.ForeignKey(help_text='The user who booked this appointment.', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['appointment_date', 'appointment_time'], name='appointment_appoint_c5b816_idx'), models.Index(fields=['status'], name='appointment_status_8fe9d7_idx'), models.Index(fields=['user', 'appointment_date'], name='appointment_user_id_06ac27_idx'), models.Index(fields=['user'], name='appointment_user_id_067c02_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'Scheduled')), fields=('appointment_date', 'appointment_time'), name='unique_scheduled_appointment_slot')],
            },
        ),
    ]
