# Generated by Django 6.0.3 on 2026-03-16 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['appointment_date', 'appointment_time']},
        ),
        migrations.AlterModelOptions(
            name='availabilityexception',
            options={'verbose_name': 'Availability Exception', 'verbose_name_plural': 'Availability Exceptions'},
        ),
        migrations.AlterModelOptions(
            name='doctoravailability',
            options={'ordering': ['day_of_week'], 'verbose_name': 'Doctor Availability', 'verbose_name_plural': 'Doctor Availabilities'},
        ),
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_scheduled_appointment_slot',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appointment_user_id_067c02_idx',
        ),
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.TextField(blank=True, help_text='Optional reason for visit.'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled_user', 'Cancelled by User'), ('cancelled_admin', 'Cancelled by Admin'), ('visited', 'Visited')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='availabilityexception',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='availabilityexception',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='availabilityexception',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='day_of_week',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], help_text='Day of the week this availability applies to.', max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='end_time',
            field=models.TimeField(help_text='End of working hours.'),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='start_time',
            field=models.TimeField(help_text='Start of working hours.'),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='time_gap',
            field=models.PositiveIntegerField(default=0, help_text='Gap between visits in minutes.'),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='visit_duration',
            field=models.PositiveIntegerField(help_text='Visit duration in minutes (e.g. 15).'),
        ),
        migrations.AddIndex(
            model_name='availabilityexception',
            index=models.Index(fields=['start_date', 'end_date'], name='appointment_start_d_772ae1_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'scheduled')), fields=('appointment_date', 'appointment_time'), name='unique_scheduled_appointment_slot'),
        ),
    ]
