# Generated by Django 5.2.11 on 2026-06-03 17:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctoravailability',
            options={'ordering': ['id'], 'verbose_name': 'Doctor Availability', 'verbose_name_plural': 'Doctor Availabilities'},
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='days_of_week',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='time_gap',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='visit_duration',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
