# Generated by Django 6.0.3 on 2026-03-15 22:35

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient Profile',
                'verbose_name_plural': 'Patient Profiles',
            },
        ),
        migrations.AddField(
            model_name='otprequest',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 15, 22, 35, 12, 71097, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='otprequest',
            index=models.Index(fields=['phone_number', 'is_used'], name='users_otpre_phone_n_b09f78_idx'),
        ),
        migrations.AddIndex(
            model_name='otprequest',
            index=models.Index(fields=['expires_at'], name='users_otpre_expires_57c04c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='users_user_phone_n_7fe504_idx'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['national_id'], name='users_patie_nationa_d4de0b_idx'),
        ),
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['date_of_birth'], name='users_patie_date_of_c633ea_idx'),
        ),
    ]
