# Generated by Django 6.1.1 on 2026-09-30 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_gateway', '0003_remove_triage_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='kind',
            field=models.CharField(blank=True, choices=[('fallback', 'Fallback message'), ('emergency_code', 'Emergency code')], default='', max_length=30),
        ),
        migrations.CreateModel(
            name='TriageAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('unknown', 'Unknown'), ('out_of_scope', 'Out of scope'), ('low_priority', 'Low priority'), ('high_priority', 'High priority'), ('urgent', 'Urgent')], max_length=20)),
                ('kind', models.CharField(choices=[('booking_offer', 'Booking offer'), ('emergency_code', 'Emergency code')], max_length=30)),
                ('emergency_code', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_actions', to='chat_gateway.chatsession')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('session', 'level'), name='uniq_triage_action_per_level')],
            },
        ),
    ]
